directory: C:\\Users\\dlarsen.NI\\Music
exclude:
  - Afterglow
  - Andrea Bocelli
  - Andrew Maxfield
  - Antonio Lucio Vivaldi
  - Berlin Symphony Orchestra
  - Bob Carlisle
  - Christmas - What's it Gonna Be, Santa
  - Les Miserables 10th Anniversary Concert
  - Conjure One
  - Conspirare
  - Danny Baranowsky
  - Dark Moor
  - Dvorak
  - Eleanor Larsen
  - Frederic Chopin
  - 15 - Once There Were Some Snowmen.mp3
  - 16 - Once There Were Some Snowmen.mp3
  - 17 - Once There Were Some Snowmen.mp3
  - 18 - Once There Were Some Snowmen.mp3
  - 19 - I Feel Cold.mp3
  - 20 - Once There Were Some Snowmen.mp3
  - 21 - Once There Were Some Snowmen.mp3
  - 22 - To the Snowmobile, Robin.mp3
  - 23 - Once There Were Some Snowmen.mp3
  - 24 - In the Sun He Melted.mp3
  - 25 - Once There Were Some Snowmen.mp3
  - 26 - 'Cause He's a Snowman.mp3
  - 27 - Small, Small, Small.mp3
  - Irving Berlin
  - Jaci Velasquez
  - James Loynes
  - Jenny Phillips
  - Johann Sebastian Bach
  - Jose Carreras
  - In Concert
  - Live at the Greek
  - Larry Knechtel
  - Lena Raine
  - Lisa Harris
  - Lonestar
  - Luciano Pavarotti
  - Ludwig van Beethoven
  - Marvin Goldstein
  - Merrill Jenson
  - As I Am
  - Safe Harbors
  - The Collection, Volume I
  - The Sum of All Grace
  - Nintendo
  - Northridge Choir
  - Orem Institute of Religion Latter-day Choir
  - Paul Cardall
  - Scripture Scouts
  - Stephen Larsen
  - Team Larsen
  - The Brigham Youn University Men's Chorus
  - The Five Browns
  - The Tabernacle Choir at Temple Square
  - University Chorale
  - A More Excellent Way
  - Allegro Classical Winter 2013 Sampler
  - Book of Mormon Video Soundtrack
  - Children's Songbook
  - Dance Classics - Ballroom
  - Doctrine and Covenants and Church History Video Soundtrack
  - Downloaded Children's Church Music
  - Echoes of the Sabbath
  - 02 - The Rising Narration.mp3
  - 04 - Candles Narration.mp3
  - 06 - American Dreams Narration.mp3
  - 08 - He Walked A Mile In My Shoes Narration.mp3
  - 10 - Say Uncle Narration.mp3
  - 12 - Emma Narration.mp3
  - 14 - Modern-Day Samson Narration.mp3
  - 16 - Brother I'll Follow You Narration.mp3
  - 18 - Lamb To The Slaughter Narration.mp3
  - 20 - Farewell Nauvoo Narration.mp3
  - LDS Hymns of Praise
  - LDS Superhits of the 90s
  - Let's Do Brunch
  - New Testament Video Soundtrack
  - Old Testament Video Songs
  - Stand in the Light
  - Summer Fever '07
  - The Classical Collection III Dove Music to Savor
  - The Hill Cumorah Pageant
  - Trek - A Nashville Tribute to the Pioneers
  - VeggieTales
  - Yasunori Mitsuda
  # Christmas
  - A Winter Symphony
  - George Frideric Handel
  - Noel
  - A Fresh Aire Christmas
  - Christmas
  - Christmas Portrait
  - Winter Serenade
  - Trans-Siberian Orchestra
