[project]
name = "mp3quiz"
version = "0.1.0"
description = "Create a \"name the artist/song\" quiz from your mp3 library."
authors = [{ name = "Daniel Larsen" }]
license = { text = "The Unlicense" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame (>=2.6.1,<3.0.0)",
    "hsaudiotag3k (>=1.1.3.post1,<2.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "mutagen (>=1.48.1,<2.0.0) ; python_version >= \"3.13\" and python_version < \"4\"",
]
scripts = { mp3quiz = "mp3quiz:main" }


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
